/*
 Navicat Premium Data Transfer

 Source Server         : localhost-oracle-system
 Source Server Type    : Oracle
 Source Server Version : 180000
 Source Host           : localhost:1521
 Source Schema         : C##YWJG

 Target Server Type    : Oracle
 Target Server Version : 180000
 File Encoding         : 65001

 Date: 22/10/2020 16:16:20
*/


-- ----------------------------
-- Table structure for RE_ROLE_PERMS
-- ----------------------------
DROP TABLE "C##YWJG"."RE_ROLE_PERMS";
CREATE TABLE "C##YWJG"."RE_ROLE_PERMS" (
  "PK_ROLEPERMS_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "FK_ROLE_ID" VARCHAR2(20 BYTE) VISIBLE,
  "FK_PERMS_ID" VARCHAR2(20 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for RE_USER_ROLE
-- ----------------------------
DROP TABLE "C##YWJG"."RE_USER_ROLE";
CREATE TABLE "C##YWJG"."RE_USER_ROLE" (
  "PK_USERROLE_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "FK_USER_ID" VARCHAR2(20 BYTE) VISIBLE,
  "FK_ROLE_ID" VARCHAR2(20 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for T_HALL_JIASHIZHENG
-- ----------------------------
DROP TABLE "C##YWJG"."T_HALL_JIASHIZHENG";
CREATE TABLE "C##YWJG"."T_HALL_JIASHIZHENG" (
  "PK_JIASHI_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "APPLICANT" VARCHAR2(15 BYTE) VISIBLE,
  "IDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "HANDLE_PEOPLE" VARCHAR2(15 BYTE) VISIBLE,
  "BUSINESS_TYPE" VARCHAR2(100 BYTE) VISIBLE,
  "DEPT_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "WITHDRAW_TYPE" VARCHAR2(50 BYTE) VISIBLE,
  "WITHDRAW_TIME" DATE VISIBLE,
  "LACK" VARCHAR2(1500 BYTE) VISIBLE,
  "REMARKS" VARCHAR2(255 BYTE) VISIBLE,
  "ASSOCIATION_NUMBER" VARCHAR2(30 BYTE) VISIBLE,
  "ORDINAL" VARCHAR2(5 BYTE) VISIBLE,
  "FILE_NUM" VARCHAR2(50 BYTE) VISIBLE,
  "DRIVING_MODEL" VARCHAR2(100 BYTE) VISIBLE,
  "OTHER_LACK" VARCHAR2(255 BYTE) VISIBLE,
  "SERIAL_NUMBER" VARCHAR2(30 BYTE) VISIBLE,
  "LICENSE_BUSINESS" VARCHAR2(100 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."APPLICANT" IS '申请人';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."IDCARD" IS '身份证件号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."HANDLE_PEOPLE" IS '经办人';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."DEPT_NAME" IS '部门名称';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."WITHDRAW_TYPE" IS '退办类型';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."WITHDRAW_TIME" IS '退办时间';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."LACK" IS '缺少项';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."REMARKS" IS '备注';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."ASSOCIATION_NUMBER" IS '关联号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."ORDINAL" IS '排队号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."FILE_NUM" IS '档案编号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."DRIVING_MODEL" IS '准驾车型';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."OTHER_LACK" IS '其他缺少项';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."SERIAL_NUMBER" IS '流水号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIASHIZHENG"."LICENSE_BUSINESS" IS '驾驶证办理业务类型';

-- ----------------------------
-- Table structure for T_HALL_JIDONGCHE
-- ----------------------------
DROP TABLE "C##YWJG"."T_HALL_JIDONGCHE";
CREATE TABLE "C##YWJG"."T_HALL_JIDONGCHE" (
  "PK_JIDONGCHE_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "DEPT_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "WITHDRAW_TYPE" VARCHAR2(50 BYTE) VISIBLE,
  "APPLICANT" VARCHAR2(15 BYTE) VISIBLE,
  "BUSINESS_TYPE" VARCHAR2(100 BYTE) VISIBLE,
  "NUMBER_TYPE" VARCHAR2(100 BYTE) VISIBLE,
  "NUMBER_PLATE" VARCHAR2(50 BYTE) VISIBLE,
  "LACK" VARCHAR2(1500 BYTE) VISIBLE,
  "HANDLE_PEOPLE" VARCHAR2(15 BYTE) VISIBLE,
  "WITHDRAW_TIME" DATE VISIBLE,
  "IDCARD" VARCHAR2(30 BYTE) VISIBLE,
  "ASSOCIATION_NUMBER" VARCHAR2(50 BYTE) VISIBLE,
  "ORDINAL" VARCHAR2(5 BYTE) VISIBLE,
  "FILE_NUM" NVARCHAR2(50) VISIBLE,
  "IDENTIFY_CODE" VARCHAR2(100 BYTE) VISIBLE,
  "OTHER_LACK" VARCHAR2(255 BYTE) VISIBLE,
  "SERIAL_NUMBER" VARCHAR2(50 BYTE) VISIBLE,
  "CAR_BUSINESS" VARCHAR2(100 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."DEPT_NAME" IS '部门名称';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."WITHDRAW_TYPE" IS '退办类型';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."APPLICANT" IS '申请人';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."NUMBER_TYPE" IS '号牌种类';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."NUMBER_PLATE" IS '号牌号码';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."LACK" IS '缺少项';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."HANDLE_PEOPLE" IS '经办人';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."WITHDRAW_TIME" IS '退办时间';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."IDCARD" IS '申请人证件号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."ASSOCIATION_NUMBER" IS '关联号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."ORDINAL" IS '排队号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."FILE_NUM" IS '档案编号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."IDENTIFY_CODE" IS '车辆识别代码';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."OTHER_LACK" IS '其他缺少项';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."SERIAL_NUMBER" IS '流水号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_JIDONGCHE"."CAR_BUSINESS" IS '机动车业务';

-- ----------------------------
-- Table structure for T_HALL_QUEUE
-- ----------------------------
DROP TABLE "C##YWJG"."T_HALL_QUEUE";
CREATE TABLE "C##YWJG"."T_HALL_QUEUE" (
  "PK_QUEUE_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "ORDINAL" VARCHAR2(10 BYTE) VISIBLE,
  "WINDOW_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "AGENT" VARCHAR2(15 BYTE) VISIBLE,
  "BUSINESS_TYPE" VARCHAR2(60 BYTE) VISIBLE,
  "A_CERTIFICATES_TYPE" VARCHAR2(30 BYTE) VISIBLE,
  "A_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "A_IDCARD" VARCHAR2(30 BYTE) VISIBLE,
  "B_CERTIFICATES_TYPE" VARCHAR2(30 BYTE) VISIBLE,
  "B_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "B_IDCARD" VARCHAR2(30 BYTE) VISIBLE,
  "GET_TIME" DATE VISIBLE,
  "START_TIME" DATE VISIBLE,
  "END_TIME" DATE VISIBLE,
  "REMARKS" VARCHAR2(30 BYTE) VISIBLE,
  "IS_VIP" NUMBER VISIBLE,
  "IDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "DAOBAN_PEOPLE" VARCHAR2(15 BYTE) VISIBLE,
  "SERIAL_NUMBER" VARCHAR2(13 BYTE) INVISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."ORDINAL" IS '排队号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."WINDOW_NAME" IS '窗口';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."AGENT" IS '经办人';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."A_CERTIFICATES_TYPE" IS '代理人证件类型';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."A_NAME" IS '代理人姓名';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."A_IDCARD" IS '代理人身份证件号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."B_CERTIFICATES_TYPE" IS '本人证件类型';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."B_NAME" IS '本人姓名';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."B_IDCARD" IS '本人身份证件号';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."GET_TIME" IS '取号时间';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."END_TIME" IS '结束时间';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."REMARKS" IS '备注';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."IS_VIP" IS '是否特呼';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."IDCARD" IS '经办人身份证';
COMMENT ON COLUMN "C##YWJG"."T_HALL_QUEUE"."DAOBAN_PEOPLE" IS '导办人';

-- ----------------------------
-- Table structure for T_HALL_TAKENUMBER
-- ----------------------------
DROP TABLE "C##YWJG"."T_HALL_TAKENUMBER";
CREATE TABLE "C##YWJG"."T_HALL_TAKENUMBER" (
  "PK_TAKENUM_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "FLAG" NUMBER VISIBLE,
  "GET_TIME" DATE VISIBLE,
  "ORDINAL" VARCHAR2(10 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_HALL_TAKENUMBER"."PK_TAKENUM_ID" IS '取号表主键';
COMMENT ON COLUMN "C##YWJG"."T_HALL_TAKENUMBER"."FLAG" IS '处理标识';
COMMENT ON COLUMN "C##YWJG"."T_HALL_TAKENUMBER"."GET_TIME" IS '取号时间';
COMMENT ON COLUMN "C##YWJG"."T_HALL_TAKENUMBER"."ORDINAL" IS '序号';

-- ----------------------------
-- Table structure for T_LIST_AGENT
-- ----------------------------
DROP TABLE "C##YWJG"."T_LIST_AGENT";
CREATE TABLE "C##YWJG"."T_LIST_AGENT" (
  "PK_AGENT_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "BUSINESS_TYPE" VARCHAR2(30 BYTE) VISIBLE,
  "A_CERTIFICATES_TYPE" VARCHAR2(20 BYTE) VISIBLE,
  "A_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "A_IDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "B_CERTIFICATES_TYPE" VARCHAR2(20 BYTE) VISIBLE,
  "B_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "B_IDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "ADD_TIME" DATE VISIBLE,
  "AGENT" VARCHAR2(15 BYTE) VISIBLE,
  "REMARKS" VARCHAR2(100 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."PK_AGENT_ID" IS '代办信息表';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."A_CERTIFICATES_TYPE" IS '代理人身份证类型';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."A_NAME" IS '代理人名字';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."A_IDCARD" IS '代理人证件号';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."B_CERTIFICATES_TYPE" IS '本人证件类型';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."B_NAME" IS '本人名称';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."B_IDCARD" IS '本人证件';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."ADD_TIME" IS '添加时间';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."AGENT" IS '经办人';
COMMENT ON COLUMN "C##YWJG"."T_LIST_AGENT"."REMARKS" IS '备注';

-- ----------------------------
-- Table structure for T_LIST_INFO
-- ----------------------------
DROP TABLE "C##YWJG"."T_LIST_INFO";
CREATE TABLE "C##YWJG"."T_LIST_INFO" (
  "PK_LIST_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "LIST_TYPE" VARCHAR2(10 BYTE) VISIBLE,
  "FULL_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "IDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "TEL" VARCHAR2(11 BYTE) VISIBLE,
  "EXPLAIN" VARCHAR2(255 BYTE) VISIBLE,
  "OTHER" VARCHAR2(255 BYTE) VISIBLE,
  "REASON" VARCHAR2(255 BYTE) VISIBLE,
  "WHETHER_PASS" VARCHAR2(10 BYTE) VISIBLE,
  "APPROVAL_PEOPLE" VARCHAR2(15 BYTE) VISIBLE,
  "UNIT" VARCHAR2(150 BYTE) VISIBLE,
  "ORGANIZATION_CODE" VARCHAR2(20 BYTE) VISIBLE,
  "APPLY_BOOK" VARCHAR2(100 BYTE) VISIBLE,
  "CODE_CERTIFICATES" VARCHAR2(100 BYTE) VISIBLE,
  "OPERATOR" VARCHAR2(15 BYTE) VISIBLE,
  "CREATE_TIME" DATE VISIBLE,
  "APPROVAL_TIME" DATE VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."PK_LIST_ID" IS '主键';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."LIST_TYPE" IS '名单类型,黑名单或者红名单';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."FULL_NAME" IS '全名';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."IDCARD" IS '身份证';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."TEL" IS '联系电话';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."EXPLAIN" IS '说明';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."OTHER" IS '其他';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."REASON" IS '理由';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."WHETHER_PASS" IS '是否通过';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."APPROVAL_PEOPLE" IS '审批人';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."UNIT" IS '单位名称';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."ORGANIZATION_CODE" IS '组织机构代码';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."APPLY_BOOK" IS '申请书';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."CODE_CERTIFICATES" IS '组织机构代码证';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."OPERATOR" IS '操作人';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."CREATE_TIME" IS '加入时间';
COMMENT ON COLUMN "C##YWJG"."T_LIST_INFO"."APPROVAL_TIME" IS '审批时间';

-- ----------------------------
-- Table structure for T_LOG_EXCEPTION
-- ----------------------------
DROP TABLE "C##YWJG"."T_LOG_EXCEPTION";
CREATE TABLE "C##YWJG"."T_LOG_EXCEPTION" (
  "PK_EXC_ID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "EXC_REQU_PARAM" VARCHAR2(100 BYTE) VISIBLE,
  "EXC_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "EXC_MSG" VARCHAR2(4000 BYTE) VISIBLE,
  "OPER_USER_ID" VARCHAR2(20 BYTE) VISIBLE,
  "OPER_USER_NAME" VARCHAR2(20 BYTE) VISIBLE,
  "OPER_METHOD" VARCHAR2(100 BYTE) VISIBLE,
  "OPER_URL" VARCHAR2(50 BYTE) VISIBLE,
  "OPER_IP" VARCHAR2(15 BYTE) VISIBLE,
  "OPER_VERSION" VARCHAR2(50 BYTE) VISIBLE,
  "EXC_TIME" DATE VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."PK_EXC_ID" IS '异常日志主键id';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."EXC_REQU_PARAM" IS '请求参数';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."EXC_NAME" IS '异常名称';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."EXC_MSG" IS '异常信息';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."OPER_USER_ID" IS '操作员id';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."OPER_USER_NAME" IS '操作员姓名';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."OPER_METHOD" IS '操作方法';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."OPER_URL" IS '请求url';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."OPER_IP" IS '请求ip';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."OPER_VERSION" IS '操作版本号';
COMMENT ON COLUMN "C##YWJG"."T_LOG_EXCEPTION"."EXC_TIME" IS '异常日志创建时间';

-- ----------------------------
-- Table structure for T_LOG_RECORD
-- ----------------------------
DROP TABLE "C##YWJG"."T_LOG_RECORD";
CREATE TABLE "C##YWJG"."T_LOG_RECORD" (
  "PK_RECORD_ID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "RECORD_MODULE" VARCHAR2(100 BYTE) VISIBLE,
  "RECORD_TYPE" VARCHAR2(50 BYTE) VISIBLE,
  "RECORD_DESC" VARCHAR2(200 BYTE) VISIBLE,
  "RECORD_REQU_PARAM" VARCHAR2(100 BYTE) VISIBLE,
  "RECORD_RESP_PARAM" VARCHAR2(100 BYTE) VISIBLE,
  "RECORD_USER_ID" VARCHAR2(20 BYTE) VISIBLE,
  "RECORD_USER_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "RECORD_FULL_NAME" VARCHAR2(20 BYTE) VISIBLE,
  "RECORD_METHOD" VARCHAR2(200 BYTE) VISIBLE,
  "RECORD_URL" VARCHAR2(50 BYTE) VISIBLE,
  "RECORD_IP" VARCHAR2(15 BYTE) VISIBLE,
  "RECORD_TIME" DATE VISIBLE,
  "RECORD_VERSION" VARCHAR2(20 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."PK_RECORD_ID" IS '日志记录主键id';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_MODULE" IS '日志记录操作功能模块';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_TYPE" IS '操作类型';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_DESC" IS '操作描述';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_REQU_PARAM" IS '请求参数';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_RESP_PARAM" IS '返回参数';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_USER_ID" IS '操作员id';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_USER_NAME" IS '操作员账户';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_FULL_NAME" IS '操作员姓名';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_METHOD" IS '操作方法';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_URL" IS '请求url';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_IP" IS 'ip';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_TIME" IS '日志创建日期';
COMMENT ON COLUMN "C##YWJG"."T_LOG_RECORD"."RECORD_VERSION" IS '操作版本号';

-- ----------------------------
-- Table structure for T_SYNTHETICAL_MAKECARD
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYNTHETICAL_MAKECARD";
CREATE TABLE "C##YWJG"."T_SYNTHETICAL_MAKECARD" (
  "PK_CARD_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "A_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "A_IDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "LICENSE_PLATE" VARCHAR2(10 BYTE) VISIBLE,
  "CREATE_TIME" DATE VISIBLE,
  "OPRATOR_PEPLE" VARCHAR2(15 BYTE) VISIBLE,
  "STATUS" VARCHAR2(20 BYTE) VISIBLE,
  "START_TIME" DATE VISIBLE,
  "END_TIME" DATE VISIBLE,
  "GET_TIME" DATE VISIBLE,
  "B_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "B_IDCARD" VARCHAR2(18 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."PK_CARD_ID" IS '制证主键id';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."A_NAME" IS '代理人姓名';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."A_IDCARD" IS '代理人身份证号';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."LICENSE_PLATE" IS '车牌号';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."OPRATOR_PEPLE" IS '操作人';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."STATUS" IS '状态,有未开始、制证中，已完成，已领取，废弃';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."END_TIME" IS '制作完成时间';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."GET_TIME" IS '领证时间';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."B_NAME" IS '本人姓名';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_MAKECARD"."B_IDCARD" IS '本人身份证';

-- ----------------------------
-- Table structure for T_SYNTHETICAL_RECORD
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYNTHETICAL_RECORD";
CREATE TABLE "C##YWJG"."T_SYNTHETICAL_RECORD" (
  "PK_RECORD_ID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "DW" VARCHAR2(100 BYTE) VISIBLE,
  "ZZJGDM" VARCHAR2(20 BYTE) VISIBLE,
  "SYR" VARCHAR2(15 BYTE) VISIBLE,
  "TEL" VARCHAR2(11 BYTE) VISIBLE,
  "WJLJ1" VARCHAR2(100 BYTE) VISIBLE,
  "WJLJ2" VARCHAR2(100 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_RECORD"."PK_RECORD_ID" IS '备案主键id';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_RECORD"."DW" IS '单位';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_RECORD"."ZZJGDM" IS '组织机构代码';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_RECORD"."SYR" IS '所有人';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_RECORD"."TEL" IS '电话';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_RECORD"."WJLJ1" IS '文件路径1';
COMMENT ON COLUMN "C##YWJG"."T_SYNTHETICAL_RECORD"."WJLJ2" IS '文件路径2';

-- ----------------------------
-- Table structure for T_SYS_BUSINESSTYPE
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYS_BUSINESSTYPE";
CREATE TABLE "C##YWJG"."T_SYS_BUSINESSTYPE" (
  "PK_BUSINESSTYPE_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "TYPE_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "TYPE_LEVEL" VARCHAR2(1 BYTE) VISIBLE,
  "WHETHER_NULL" NUMBER(1,0) VISIBLE,
  "REMARKS" VARCHAR2(255 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYS_BUSINESSTYPE"."PK_BUSINESSTYPE_ID" IS '业务类型主键';
COMMENT ON COLUMN "C##YWJG"."T_SYS_BUSINESSTYPE"."TYPE_NAME" IS '业务名称';
COMMENT ON COLUMN "C##YWJG"."T_SYS_BUSINESSTYPE"."TYPE_LEVEL" IS '业务级别';
COMMENT ON COLUMN "C##YWJG"."T_SYS_BUSINESSTYPE"."WHETHER_NULL" IS '是否为备用业务类型';
COMMENT ON COLUMN "C##YWJG"."T_SYS_BUSINESSTYPE"."REMARKS" IS '备注';

-- ----------------------------
-- Table structure for T_SYS_DEPT
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYS_DEPT";
CREATE TABLE "C##YWJG"."T_SYS_DEPT" (
  "PK_DEPT_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "DEPT_NAME" VARCHAR2(30 BYTE) VISIBLE,
  "DEPT_UNIT" VARCHAR2(30 BYTE) VISIBLE,
  "DEPT_ADDRESS" VARCHAR2(50 BYTE) VISIBLE,
  "CREATE_TIME" DATE VISIBLE,
  "MECHANISM" VARCHAR2(50 BYTE) VISIBLE,
  "DEPT_LEVEL" VARCHAR2(1 BYTE) VISIBLE,
  "SUPERIOR_DEPT" VARCHAR2(30 BYTE) VISIBLE,
  "PEOPLE" VARCHAR2(15 BYTE) VISIBLE,
  "TEL" VARCHAR2(11 BYTE) VISIBLE,
  "ISSUING_AUTHORITY" VARCHAR2(50 BYTE) VISIBLE,
  "FAX" VARCHAR2(20 BYTE) VISIBLE,
  "REMARKS" VARCHAR2(255 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."DEPT_NAME" IS '部门名称';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."DEPT_UNIT" IS '部门单位';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."DEPT_ADDRESS" IS '部门地址';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."MECHANISM" IS '备案机构';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."DEPT_LEVEL" IS '部门级别';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."SUPERIOR_DEPT" IS '上级部门';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."PEOPLE" IS '联系人';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."TEL" IS '联系电话';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."ISSUING_AUTHORITY" IS '发证机关';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."FAX" IS '传真';
COMMENT ON COLUMN "C##YWJG"."T_SYS_DEPT"."REMARKS" IS '备注';

-- ----------------------------
-- Table structure for T_SYS_PARAM
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYS_PARAM";
CREATE TABLE "C##YWJG"."T_SYS_PARAM" (
  "PK_PARAM_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "PARAM_KEY" VARCHAR2(100 BYTE) VISIBLE,
  "PARAM_VALUE" VARCHAR2(30 BYTE) VISIBLE,
  "OPERATOR_PEOPLE" VARCHAR2(15 BYTE) VISIBLE,
  "OPERATOR_TIME" DATE VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYS_PARAM"."PARAM_KEY" IS '参数名';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PARAM"."PARAM_VALUE" IS '参数值';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PARAM"."OPERATOR_PEOPLE" IS '操作人';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PARAM"."OPERATOR_TIME" IS '操作时间';

-- ----------------------------
-- Table structure for T_SYS_PERMS
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYS_PERMS";
CREATE TABLE "C##YWJG"."T_SYS_PERMS" (
  "PK_PERMS_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "P_ID" VARCHAR2(20 BYTE) VISIBLE,
  "MENU_NAME" VARCHAR2(40 BYTE) VISIBLE,
  "PATH" VARCHAR2(30 BYTE) VISIBLE,
  "PERMS_CODE" VARCHAR2(20 BYTE) VISIBLE,
  "TYPE" VARCHAR2(1 BYTE) VISIBLE,
  "CREATE_TIME" DATE VISIBLE,
  "MODIFY_TIME" DATE VISIBLE,
  "MODIFY_USERNAME" VARCHAR2(15 BYTE) VISIBLE,
  "FK_USER_ID" VARCHAR2(20 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."P_ID" IS '父级菜单';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."MENU_NAME" IS '菜单名称';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."PATH" IS '路由路径';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."PERMS_CODE" IS '权限码';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."TYPE" IS '菜单类型，1代表模块2类别3主菜单4按钮';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."MODIFY_TIME" IS '修改时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."MODIFY_USERNAME" IS '修改人名字';
COMMENT ON COLUMN "C##YWJG"."T_SYS_PERMS"."FK_USER_ID" IS '修改人id';

-- ----------------------------
-- Table structure for T_SYS_ROLE
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYS_ROLE";
CREATE TABLE "C##YWJG"."T_SYS_ROLE" (
  "PK_ROLE_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "ROLE_NAME" VARCHAR2(30 BYTE) VISIBLE,
  "ROLE_DESC" VARCHAR2(50 BYTE) VISIBLE,
  "CREATE_DATE" DATE VISIBLE,
  "ENABLE_STATUS" NUMBER(1,0) VISIBLE,
  "MODIFY_TIME" DATE VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYS_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "C##YWJG"."T_SYS_ROLE"."ROLE_DESC" IS '角色描述';
COMMENT ON COLUMN "C##YWJG"."T_SYS_ROLE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_ROLE"."ENABLE_STATUS" IS '启用状态，1启用，0禁用';
COMMENT ON COLUMN "C##YWJG"."T_SYS_ROLE"."MODIFY_TIME" IS '修改时间';

-- ----------------------------
-- Table structure for T_SYS_TOKEN
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYS_TOKEN";
CREATE TABLE "C##YWJG"."T_SYS_TOKEN" (
  "PK_TOKEN_ID" VARCHAR2(35 BYTE) VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(20 BYTE) VISIBLE,
  "PASSWORD" VARCHAR2(35 BYTE) VISIBLE,
  "IP" VARCHAR2(30 BYTE) VISIBLE,
  "FULL_NAME" VARCHAR2(30 BYTE) VISIBLE,
  "POLICE_NUM" VARCHAR2(7 BYTE) VISIBLE,
  "FK_USER_ID" NUMBER(20,0) VISIBLE,
  "EXPIRE_TIME" DATE VISIBLE,
  "UPDATE_TIME" DATE VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."PK_TOKEN_ID" IS 'tokenID';
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."USERNAME" IS '用户名';
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."PASSWORD" IS '密码';
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."IP" IS 'ip地址';
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."FULL_NAME" IS '全名';
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."POLICE_NUM" IS '警号';
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."FK_USER_ID" IS '用户id';
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."EXPIRE_TIME" IS '过期时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_TOKEN"."UPDATE_TIME" IS '更新时间';

-- ----------------------------
-- Table structure for T_SYS_USER
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYS_USER";
CREATE TABLE "C##YWJG"."T_SYS_USER" (
  "PK_USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(20 BYTE) VISIBLE,
  "PASSWORD" VARCHAR2(35 BYTE) VISIBLE,
  "LAST_LOGIN_DATE" DATE VISIBLE,
  "FK_DEPT_ID" VARCHAR2(20 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(30 BYTE) VISIBLE,
  "TEL" VARCHAR2(11 BYTE) VISIBLE,
  "ENABLE_STATUS" NUMBER(1,0) VISIBLE,
  "CREATE_TIME" DATE VISIBLE,
  "IDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "MODIFY_TIME" DATE VISIBLE,
  "FULL_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "POLICE_NUM" VARCHAR2(7 BYTE) VISIBLE,
  "UNIT" VARCHAR2(20 BYTE) VISIBLE,
  "ON_LINE" NUMBER(1,0) VISIBLE,
  "IP" VARCHAR2(30 BYTE) VISIBLE,
  "ADDRESS" VARCHAR2(100 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."LAST_LOGIN_DATE" IS '最后一次登录时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."FK_DEPT_ID" IS '部门id';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."TEL" IS '联系电话';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."ENABLE_STATUS" IS '状态,1启用 0禁用';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."IDCARD" IS '身份证';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."MODIFY_TIME" IS '修改时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."FULL_NAME" IS '真实姓名';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."POLICE_NUM" IS '警号';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."UNIT" IS '单位';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."ON_LINE" IS '在线状态，1在线0离线';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."IP" IS 'ip';
COMMENT ON COLUMN "C##YWJG"."T_SYS_USER"."ADDRESS" IS '联系地址';

-- ----------------------------
-- Table structure for T_SYS_WINDOW
-- ----------------------------
DROP TABLE "C##YWJG"."T_SYS_WINDOW";
CREATE TABLE "C##YWJG"."T_SYS_WINDOW" (
  "PK_WINDOW_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "DEPT_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "WINDOW_NAME" VARCHAR2(20 BYTE) VISIBLE,
  "IP" VARCHAR2(15 BYTE) VISIBLE,
  "BUSINESS_TYPE" VARCHAR2(255 BYTE) VISIBLE,
  "OPERATOR_PEOPLE" VARCHAR2(30 BYTE) VISIBLE,
  "OPERATOR_TIME" DATE VISIBLE,
  "CONTROL_CARD" VARCHAR2(255 BYTE) VISIBLE,
  "REMARKS" VARCHAR2(50 BYTE) VISIBLE,
  "BRANCH_NUMBER" VARCHAR2(50 BYTE) VISIBLE,
  "REGISTRATION_WINDOW" VARCHAR2(20 BYTE) VISIBLE,
  "COM" VARCHAR2(100 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."DEPT_NAME" IS '部门名称';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."WINDOW_NAME" IS '窗口名称';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."IP" IS 'ip';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."OPERATOR_PEOPLE" IS '操作人';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."OPERATOR_TIME" IS '操作时间';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."CONTROL_CARD" IS '控制卡';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."REMARKS" IS '备注';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."BRANCH_NUMBER" IS '网点编号';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."REGISTRATION_WINDOW" IS '注册窗口号';
COMMENT ON COLUMN "C##YWJG"."T_SYS_WINDOW"."COM" IS '评价器com号';

-- ----------------------------
-- Table structure for T_WARN_LNFO
-- ----------------------------
DROP TABLE "C##YWJG"."T_WARN_LNFO";
CREATE TABLE "C##YWJG"."T_WARN_LNFO" (
  "PK_WARNING_ID" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "WARNING_CATEGORY" VARCHAR2(50 BYTE) VISIBLE,
  "WARNING_TYPE" VARCHAR2(150 BYTE) VISIBLE,
  "WARNING_REASON" VARCHAR2(200 BYTE) VISIBLE,
  "WARNING_DATE" DATE VISIBLE,
  "WARNING_SERIAL" VARCHAR2(13 BYTE) VISIBLE,
  "DAOBANPEOPLE" VARCHAR2(15 BYTE) VISIBLE,
  "ISAGENT" VARCHAR2(15 BYTE) VISIBLE,
  "BUSINESSTYPE" VARCHAR2(100 BYTE) VISIBLE,
  "ORDINAL" VARCHAR2(5 BYTE) VISIBLE,
  "WINDOW_NAME" VARCHAR2(15 BYTE) VISIBLE,
  "AGENT" VARCHAR2(15 BYTE) VISIBLE,
  "IDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "A_CERTIFICATES_TYPE" VARCHAR2(50 BYTE) VISIBLE,
  "ANAME" VARCHAR2(15 BYTE) VISIBLE,
  "AIDCARD" VARCHAR2(255 BYTE) VISIBLE,
  "BCERTIFICATESTYPE" VARCHAR2(50 BYTE) VISIBLE,
  "BNAME" VARCHAR2(15 BYTE) VISIBLE,
  "BIDCARD" VARCHAR2(18 BYTE) VISIBLE,
  "GET_TIME" DATE VISIBLE,
  "START_TIME" DATE VISIBLE,
  "ENDTIME" DATE VISIBLE,
  "SERIAL_NUMBER_A" VARCHAR2(13 BYTE) VISIBLE,
  "CHECK_STATUS" VARCHAR2(10 BYTE) VISIBLE,
  "CHECK_RESULT" VARCHAR2(10 BYTE) VISIBLE,
  "CHECK_DESC" VARCHAR2(900 BYTE) VISIBLE,
  "CHECK_DATE" DATE VISIBLE,
  "CHECK_PEOPLE" VARCHAR2(30 BYTE) VISIBLE,
  "CHECK_FILE" VARCHAR2(255 BYTE) VISIBLE,
  "HANDLE_STATUS" VARCHAR2(50 BYTE) VISIBLE,
  "SERIAL_NUMBER_B" VARCHAR2(100 BYTE) VISIBLE,
  "CHEZHU_XM" VARCHAR2(15 BYTE) VISIBLE,
  "CHEZHU_CARD" VARCHAR2(30 BYTE) VISIBLE,
  "HPZL" VARCHAR2(50 BYTE) VISIBLE,
  "HPHM" VARCHAR2(30 BYTE) VISIBLE,
  "CLSBDH" VARCHAR2(100 BYTE) VISIBLE,
  "SYXZ" VARCHAR2(50 BYTE) VISIBLE
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."PK_WARNING_ID" IS '预警主键id';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."WARNING_CATEGORY" IS '预警类别-取号预警、叫号预警、办理预警';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."WARNING_TYPE" IS '预警分类';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."WARNING_REASON" IS '预警原因';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."WARNING_DATE" IS '预警时间';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."WARNING_SERIAL" IS '预警流水号';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."DAOBANPEOPLE" IS '导办人';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."ISAGENT" IS '办理类型-本人业务、代理业务';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."BUSINESSTYPE" IS '办理业务类型';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."ORDINAL" IS '排队号码';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."WINDOW_NAME" IS '办理窗口';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."AGENT" IS '经办人';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."IDCARD" IS '经办人身份证';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."A_CERTIFICATES_TYPE" IS '代理人证件类型';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."ANAME" IS '代理人姓名';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."AIDCARD" IS '代理人证件号';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."BCERTIFICATESTYPE" IS '当事人证件类型';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."BNAME" IS '当事人姓名';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."BIDCARD" IS '当事人证件号';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."GET_TIME" IS '取号时间';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."ENDTIME" IS '结束时间';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."SERIAL_NUMBER_A" IS '驾驶证关联流水号';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CHECK_STATUS" IS '核查状态-待核查、已核查';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CHECK_RESULT" IS '核查结果-正常、异常';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CHECK_DESC" IS '核查说明';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CHECK_DATE" IS '核查时间';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CHECK_PEOPLE" IS '核查人';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CHECK_FILE" IS '核查附件';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."HANDLE_STATUS" IS '处理状态';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."SERIAL_NUMBER_B" IS '机动车关联流水号';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CHEZHU_XM" IS '车主姓名';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CHEZHU_CARD" IS '车主证件号';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."HPZL" IS '号牌种类';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."HPHM" IS '号牌号码';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."CLSBDH" IS '车辆识别代号';
COMMENT ON COLUMN "C##YWJG"."T_WARN_LNFO"."SYXZ" IS '使用性质';

-- ----------------------------
-- Primary Key structure for table RE_ROLE_PERMS
-- ----------------------------
ALTER TABLE "C##YWJG"."RE_ROLE_PERMS" ADD CONSTRAINT "SYS_C008943" PRIMARY KEY ("PK_ROLEPERMS_ID");

-- ----------------------------
-- Checks structure for table RE_ROLE_PERMS
-- ----------------------------
ALTER TABLE "C##YWJG"."RE_ROLE_PERMS" ADD CONSTRAINT "SYS_C0059207" CHECK (pk_rolePerms_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."RE_ROLE_PERMS" ADD CONSTRAINT "SYS_C007303" CHECK ("PK_ROLEPERMS_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."RE_ROLE_PERMS" ADD CONSTRAINT "SYS_C007434" CHECK ("PK_ROLEPERMS_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."RE_ROLE_PERMS" ADD CONSTRAINT "SYS_C009325" CHECK (pk_rolePerms_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RE_USER_ROLE
-- ----------------------------
ALTER TABLE "C##YWJG"."RE_USER_ROLE" ADD CONSTRAINT "SYS_C008612" PRIMARY KEY ("PK_USERROLE_ID");

-- ----------------------------
-- Checks structure for table RE_USER_ROLE
-- ----------------------------
ALTER TABLE "C##YWJG"."RE_USER_ROLE" ADD CONSTRAINT "SYS_C0059045" CHECK ("PK_USERROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."RE_USER_ROLE" ADD CONSTRAINT "SYS_C007304" CHECK ("PK_USERROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."RE_USER_ROLE" ADD CONSTRAINT "SYS_C007438" CHECK ("PK_USERROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."RE_USER_ROLE" ADD CONSTRAINT "SYS_C009326" CHECK (pk_userRole_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_HALL_JIASHIZHENG
-- ----------------------------
ALTER TABLE "C##YWJG"."T_HALL_JIASHIZHENG" ADD CONSTRAINT "SYS_C008952" PRIMARY KEY ("PK_JIASHI_ID");

-- ----------------------------
-- Checks structure for table T_HALL_JIASHIZHENG
-- ----------------------------
ALTER TABLE "C##YWJG"."T_HALL_JIASHIZHENG" ADD CONSTRAINT "SYS_C0059064" CHECK ("PK_JIASHI_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_JIASHIZHENG" ADD CONSTRAINT "SYS_C007392" CHECK ("PK_JIASHI_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_JIASHIZHENG" ADD CONSTRAINT "SYS_C007442" CHECK ("PK_JIASHI_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_JIASHIZHENG" ADD CONSTRAINT "SYS_C009328" CHECK (pk_jiashi_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_HALL_JIDONGCHE
-- ----------------------------
ALTER TABLE "C##YWJG"."T_HALL_JIDONGCHE" ADD CONSTRAINT "SYS_C008951" PRIMARY KEY ("PK_JIDONGCHE_ID");

-- ----------------------------
-- Checks structure for table T_HALL_JIDONGCHE
-- ----------------------------
ALTER TABLE "C##YWJG"."T_HALL_JIDONGCHE" ADD CONSTRAINT "SYS_C0059067" CHECK ("PK_JIDONGCHE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_JIDONGCHE" ADD CONSTRAINT "SYS_C007397" CHECK ("PK_JIDONGCHE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_JIDONGCHE" ADD CONSTRAINT "SYS_C007446" CHECK ("PK_JIDONGCHE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_JIDONGCHE" ADD CONSTRAINT "SYS_C009329" CHECK (pk_jidongche_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_HALL_QUEUE
-- ----------------------------
ALTER TABLE "C##YWJG"."T_HALL_QUEUE" ADD CONSTRAINT "SYS_C008950" PRIMARY KEY ("PK_QUEUE_ID");

-- ----------------------------
-- Checks structure for table T_HALL_QUEUE
-- ----------------------------
ALTER TABLE "C##YWJG"."T_HALL_QUEUE" ADD CONSTRAINT "SYS_C0059058" CHECK ("PK_QUEUE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_QUEUE" ADD CONSTRAINT "SYS_C0060365" CHECK ("PK_QUEUE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_QUEUE" ADD CONSTRAINT "SYS_C007307" CHECK ("PK_QUEUE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_QUEUE" ADD CONSTRAINT "SYS_C007450" CHECK ("PK_QUEUE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_QUEUE" ADD CONSTRAINT "SYS_C009330" CHECK (pk_queue_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_HALL_TAKENUMBER
-- ----------------------------
ALTER TABLE "C##YWJG"."T_HALL_TAKENUMBER" ADD CONSTRAINT "SYS_C008949" PRIMARY KEY ("PK_TAKENUM_ID");

-- ----------------------------
-- Checks structure for table T_HALL_TAKENUMBER
-- ----------------------------
ALTER TABLE "C##YWJG"."T_HALL_TAKENUMBER" ADD CONSTRAINT "SYS_C0059055" CHECK ("PK_TAKENUM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_TAKENUMBER" ADD CONSTRAINT "SYS_C007308" CHECK ("PK_TAKENUM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_TAKENUMBER" ADD CONSTRAINT "SYS_C007455" CHECK ("PK_TAKENUM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_HALL_TAKENUMBER" ADD CONSTRAINT "SYS_C009331" CHECK (pk_takeNum_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_LIST_AGENT
-- ----------------------------
ALTER TABLE "C##YWJG"."T_LIST_AGENT" ADD CONSTRAINT "SYS_C008948" PRIMARY KEY ("PK_AGENT_ID");

-- ----------------------------
-- Checks structure for table T_LIST_AGENT
-- ----------------------------
ALTER TABLE "C##YWJG"."T_LIST_AGENT" ADD CONSTRAINT "SYS_C0059051" CHECK ("PK_AGENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LIST_AGENT" ADD CONSTRAINT "SYS_C007309" CHECK ("PK_AGENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LIST_AGENT" ADD CONSTRAINT "SYS_C007459" CHECK ("PK_AGENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LIST_AGENT" ADD CONSTRAINT "SYS_C008947" CHECK (pk_agent_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LIST_AGENT" ADD CONSTRAINT "SYS_C009327" CHECK (pk_agent_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_LIST_INFO
-- ----------------------------
ALTER TABLE "C##YWJG"."T_LIST_INFO" ADD CONSTRAINT "SYS_C0010161" PRIMARY KEY ("PK_LIST_ID");

-- ----------------------------
-- Checks structure for table T_LIST_INFO
-- ----------------------------
ALTER TABLE "C##YWJG"."T_LIST_INFO" ADD CONSTRAINT "SYS_C0010160" CHECK (pk_list_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LIST_INFO" ADD CONSTRAINT "SYS_C0010192" CHECK (pk_list_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LIST_INFO" ADD CONSTRAINT "SYS_C0059199" CHECK (pk_list_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LIST_INFO" ADD CONSTRAINT "SYS_C007310" CHECK ("PK_LIST_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LIST_INFO" ADD CONSTRAINT "SYS_C007464" CHECK ("PK_LIST_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_LOG_EXCEPTION
-- ----------------------------
ALTER TABLE "C##YWJG"."T_LOG_EXCEPTION" ADD CONSTRAINT "SYS_C007467" PRIMARY KEY ("PK_EXC_ID");

-- ----------------------------
-- Checks structure for table T_LOG_EXCEPTION
-- ----------------------------
ALTER TABLE "C##YWJG"."T_LOG_EXCEPTION" ADD CONSTRAINT "SYS_C007466" CHECK ("PK_EXC_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_LOG_RECORD
-- ----------------------------
ALTER TABLE "C##YWJG"."T_LOG_RECORD" ADD CONSTRAINT "SYS_C007465" PRIMARY KEY ("PK_RECORD_ID");

-- ----------------------------
-- Checks structure for table T_LOG_RECORD
-- ----------------------------
ALTER TABLE "C##YWJG"."T_LOG_RECORD" ADD CONSTRAINT "SYS_C007471" CHECK ("PK_RECORD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_LOG_RECORD" ADD CONSTRAINT "SYS_C017464" CHECK ("PK_RECORD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYNTHETICAL_MAKECARD
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYNTHETICAL_MAKECARD" ADD CONSTRAINT "SYS_C0011131" PRIMARY KEY ("PK_CARD_ID");

-- ----------------------------
-- Checks structure for table T_SYNTHETICAL_MAKECARD
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYNTHETICAL_MAKECARD" ADD CONSTRAINT "SYS_C0011130" CHECK (pk_card_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYNTHETICAL_MAKECARD" ADD CONSTRAINT "SYS_C0059591" CHECK (pk_card_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYNTHETICAL_MAKECARD" ADD CONSTRAINT "SYS_C007311" CHECK ("PK_CARD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYNTHETICAL_MAKECARD" ADD CONSTRAINT "SYS_C007469" CHECK ("PK_CARD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYNTHETICAL_RECORD
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYNTHETICAL_RECORD" ADD CONSTRAINT "SYS_C007475" PRIMARY KEY ("PK_RECORD_ID");

-- ----------------------------
-- Checks structure for table T_SYNTHETICAL_RECORD
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYNTHETICAL_RECORD" ADD CONSTRAINT "SYS_C007474" CHECK ("PK_RECORD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYS_BUSINESSTYPE
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_BUSINESSTYPE" ADD CONSTRAINT "SYS_C008946" PRIMARY KEY ("PK_BUSINESSTYPE_ID");

-- ----------------------------
-- Checks structure for table T_SYS_BUSINESSTYPE
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_BUSINESSTYPE" ADD CONSTRAINT "SYS_C0059039" CHECK ("PK_BUSINESSTYPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_BUSINESSTYPE" ADD CONSTRAINT "SYS_C007312" CHECK ("PK_BUSINESSTYPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_BUSINESSTYPE" ADD CONSTRAINT "SYS_C007473" CHECK ("PK_BUSINESSTYPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_BUSINESSTYPE" ADD CONSTRAINT "SYS_C009332" CHECK (pk_businessType_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYS_DEPT
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_DEPT" ADD CONSTRAINT "SYS_C008944" PRIMARY KEY ("PK_DEPT_ID");

-- ----------------------------
-- Checks structure for table T_SYS_DEPT
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_DEPT" ADD CONSTRAINT "SYS_C0059036" CHECK ("PK_DEPT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_DEPT" ADD CONSTRAINT "SYS_C007313" CHECK ("PK_DEPT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_DEPT" ADD CONSTRAINT "SYS_C007477" CHECK ("PK_DEPT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_DEPT" ADD CONSTRAINT "SYS_C009333" CHECK (pk_dept_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYS_PARAM
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_PARAM" ADD CONSTRAINT "SYS_C0010771" PRIMARY KEY ("PK_PARAM_ID");

-- ----------------------------
-- Checks structure for table T_SYS_PARAM
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_PARAM" ADD CONSTRAINT "SYS_C0010770" CHECK (pk_param_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_PARAM" ADD CONSTRAINT "SYS_C0010775" CHECK (pk_param_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_PARAM" ADD CONSTRAINT "SYS_C0059262" CHECK (pk_param_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_PARAM" ADD CONSTRAINT "SYS_C007314" CHECK ("PK_PARAM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_PARAM" ADD CONSTRAINT "SYS_C007481" CHECK ("PK_PARAM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYS_PERMS
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_PERMS" ADD CONSTRAINT "SYS_C008942" PRIMARY KEY ("PK_PERMS_ID");

-- ----------------------------
-- Checks structure for table T_SYS_PERMS
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_PERMS" ADD CONSTRAINT "SYS_C0059203" CHECK (pk_perms_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_PERMS" ADD CONSTRAINT "SYS_C007315" CHECK ("PK_PERMS_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_PERMS" ADD CONSTRAINT "SYS_C007486" CHECK ("PK_PERMS_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_PERMS" ADD CONSTRAINT "SYS_C008941" CHECK (pk_perms_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_PERMS" ADD CONSTRAINT "SYS_C009334" CHECK (pk_perms_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYS_ROLE
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_ROLE" ADD CONSTRAINT "SYS_C008611" PRIMARY KEY ("PK_ROLE_ID");

-- ----------------------------
-- Checks structure for table T_SYS_ROLE
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_ROLE" ADD CONSTRAINT "SYS_C0059027" CHECK ("PK_ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_ROLE" ADD CONSTRAINT "SYS_C007316" CHECK ("PK_ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_ROLE" ADD CONSTRAINT "SYS_C007491" CHECK ("PK_ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_ROLE" ADD CONSTRAINT "SYS_C009335" CHECK (pk_role_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYS_TOKEN
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_TOKEN" ADD CONSTRAINT "SYS_C009550" PRIMARY KEY ("PK_TOKEN_ID");

-- ----------------------------
-- Checks structure for table T_SYS_TOKEN
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_TOKEN" ADD CONSTRAINT "SYS_C0059030" CHECK ("PK_TOKEN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_TOKEN" ADD CONSTRAINT "SYS_C007317" CHECK ("PK_TOKEN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_TOKEN" ADD CONSTRAINT "SYS_C007498" CHECK ("PK_TOKEN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYS_USER
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_USER" ADD CONSTRAINT "SYS_C007981" PRIMARY KEY ("PK_USER_ID");

-- ----------------------------
-- Checks structure for table T_SYS_USER
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_USER" ADD CONSTRAINT "SYS_C0059061" CHECK ("PK_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_USER" ADD CONSTRAINT "SYS_C007318" CHECK ("PK_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_USER" ADD CONSTRAINT "SYS_C007505" CHECK ("PK_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_USER" ADD CONSTRAINT "SYS_C009336" CHECK (pk_user_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_SYS_WINDOW
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_WINDOW" ADD CONSTRAINT "SYS_C008945" PRIMARY KEY ("PK_WINDOW_ID");

-- ----------------------------
-- Checks structure for table T_SYS_WINDOW
-- ----------------------------
ALTER TABLE "C##YWJG"."T_SYS_WINDOW" ADD CONSTRAINT "SYS_C0059024" CHECK ("PK_WINDOW_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_WINDOW" ADD CONSTRAINT "SYS_C007319" CHECK ("PK_WINDOW_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_WINDOW" ADD CONSTRAINT "SYS_C007501" CHECK ("PK_WINDOW_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##YWJG"."T_SYS_WINDOW" ADD CONSTRAINT "SYS_C009337" CHECK (pk_window_id IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table T_WARN_LNFO
-- ----------------------------
ALTER TABLE "C##YWJG"."T_WARN_LNFO" ADD CONSTRAINT "SYS_C007460" PRIMARY KEY ("PK_WARNING_ID");

-- ----------------------------
-- Checks structure for table T_WARN_LNFO
-- ----------------------------
ALTER TABLE "C##YWJG"."T_WARN_LNFO" ADD CONSTRAINT "SYS_C017459" CHECK ("PK_WARNING_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
